name: Type Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Install uv
        run: |
          pip install uv
      
      - name: Install dependencies
        run: |
          uv sync --dev
      
      - name: Run Type Checks
        run: |
          uv run mypy
      