name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.13]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
      
      - name: Install uv
        run: |
          pip install uv
      
      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Set up PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: orbitalmltestdb
          postgresql user: orbitalmltestuser
          postgresql password: orbitalmltestpassword

      - name: Run Test Suite
        run: |
          uv run pytest -v --tb=short --disable-warnings --maxfail=1 --cov=orbitalml
